### ISSUE TITLE
Purchased Pro License in September haven't recieved it yet

### ISSUE THREAD

**Issue by evaldescu-japay** [marcinguy/betterscan-ce#133]
Hello:

I purchased the pro licence via the betterscan.io webpage and haven't recieved it yet, how can I get it?

**Comment by marcinguy** [comment]
hi @evaldescu-japay 

Thank you for raising this issue.

Please contact at [contact form](https://www.betterscan.io/contact) or via hello@betterscan.io

Thanks,

**Comment by evaldescu-japay** [comment]
Hello,

Done. Hope I can receive it soon. I sent it via a different account since my work email has strict antispam policies and might be getting rejected.
