### ISSUE TITLE
No space left on device during build

### ISSUE THREAD

**Issue by sertal70** [marcinguy/betterscan-ce#140]
Hello,
as per README instructions, I tried to clone the repo on macOS 13.6.1 and start it, this is the output:

```shell
$ ./start.sh
[+] Running 142/4
 ⠼ server 36 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulling                                                             292.4s
 ✔ postgres 14 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                  289.5s
 ⠼ worker_1 82 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulling             292.4s
 ⠼ rabbitmq3 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulling                                                                                      292.4s
failed to register layer: write /usr/local/lib/python3.8/site-packages/pylint/test/messages/func_e0204.txt: no space left on device
```
My docker configuration reserves as much as 64GB of disk space for virtual disks, the host has 38GB free: is that not enough for installation?

**Comment by marcinguy** [comment]
Hi @sertal70 

Thank you for raising this issue.

What are the reasons of not using Dockerhub built images (paid account, secure environment, official images, 2 factor authentication on account, also enabled Docker Scout against malware, potential vulnerabilities, dependencies)?

It should work and use little space (builds work on Linux laptop and obviously Dockerhub)

**Comment by sertal70** [comment]
Hi @marcinguy 
simply because I'm giving a try to this tool and the first thing I do in such cases is to follow README instructions. What is wrong with that?

**Comment by marcinguy** [comment]
Nothing is wrong with that. Yes, feel free to follow instructions as you wish.

**Comment by sertal70** [comment]
You closed the issue, so I presume from your answer the only way to give a try to the tool is by using the paid version. Maybe could be worth specifying it in the README, just to be fair with others.

**Comment by marcinguy** [comment]
@sertal70 It is there, in the first line (maybe you did not see it, checked it)

**Comment by sertal70** [comment]
@marcinguy the first line only specifies differences between paid an CE version. It says nothing about the fact it is impossible to build the CE using docker and official instructions because of the error reported in  this issue, which remains unmanaged and unresolved.

**Comment by marcinguy** [comment]
@sertal70 I wrote before that builds work in Dockerhub, as well as local (Ubuntu 22.04 LTS with standard docker). I recall MacOs users also being able in the past to build it. I do not have MacOs so cannot help here more.

**Comment by sertal70** [comment]
@marcinguy I would suggest you to entirely disable the Issue section of this repo, because it is evident by this that there is no support to people who would give your product a try. Luckily, there are many other solutions around, so thank you and goodbye.
