### ISSUE TITLE
Adding custom rules?

### ISSUE THREAD

**Issue by matchett808-gh** [marcinguy/betterscan-ce#47]
Couldn't find any documentation to this effect (PR's welcome?)

How would one add custom semgrep rules?

**Comment by marcinguy** [comment]
Hi @matchett808-gh

Thank you for your issue. Please DM me, if you have basic Python/optionally ReactJS skills and want to do it and/or contribute to the project I can guide you.

What rules do you want to add? Do you own them? 

Thanks,

**Comment by matchett808-gh** [comment]
it was more that we had internal standards that weren't represented - looking at the semgrep documentation it should be possible to represent them in semgrep - but likely wouldn't be of interest to anyone else

I'm actually changing positions at the moment so my requirements have dissipated - however I'm using this in my homelab so might find another requirement - I'll start having a look when I come across my next requirement :)
