### ISSUE TITLE
Dependency files should always be scanned

### ISSUE THREAD

**Issue by carlin-q-scott** [marcinguy/betterscan-ce#81]
### Issue
I ran osv-scan directly against my project, and it detected 4 vulnerable packages, but betterscan didn't find any. I expected the scan reports to match.

[npm vulnerability scans.zip](https://github.com/marcinguy/betterscan-ce/files/10385252/npm.vulnerability.scans.zip)

I also included results for OWASP depedency-check in the zipfile since it provided similar results to osv-scan, but osv-scan has been more thorough in my testing against node.js and nuget projects.

### Theory
I'm wondering if the issue I'm seeing is that the package-lock.json was updated in a commit that had been scanned before BetterScan added the osv-scan tool. It takes hours to run BetterScan against all commits in the repo, so I have not attempted to verify this yet.

### Version Info
I used the latest version of all of these tools as of today, 1/10/2023.

**Comment by marcinguy** [comment]
@carlin-q-scott Away from the keyboard. Theoretically you can modify the file `package-lock.json` or remove it from state db

Osv-scanner should be working, as well as others.

**Comment by carlin-q-scott** [comment]
I like your idea of always scanning dependency files. That alleviates my main concern in this issue. 

I can open separate issues calling out various fields I'd like to see in my BetterScan report; issue per scanner? And if I have time I'll look into implementing those improvements myself.

**Comment by carlin-q-scott** [comment]
For the sake of efficiency, I'd imagine it would be best to only scan head for dependency issues, rather than each commit snapshot.

**Comment by marcinguy** [comment]
Thank you @carlin-q-scott 

I think you can either modify each lockfile (new line or something?), maybe 2 commits, one modification other revert? maybe easier to do or go through state database and remove entries for package files.

If you can contribute with a script, could be great (possibly also for other state db mangling)
