### ISSUE TITLE
setup fails to create tasks directory and blocks worker from working on tasks

### ISSUE THREAD

**Issue by carlin-q-scott** [marcinguy/betterscan-ce#89]
When I run `docker-compose up` in the dockerhub directory for this repo, it creates two folders, data1 and data2. The worker then attempts to create log files in data2/tasks, but that directory doesn't exist, so the worker fails to run the task. Simply creating the tasks directory solves the issue.

The setup script should run mkdir on that directory so that the worker can write its logs.

**Comment by marcinguy** [comment]
@carlin-q-scott Idea is good. I create those dirs in `start.sh` script. There is some logic not to setup the system on next run, only on initial. If you know how to make it altogether, feel free to PR. P.S Somehow the directories are created under root in Linux when running Docker as a normal user. This needs to be also taken into consideration (reading them, removing needs super user rights)

**Comment by marcinguy** [comment]
@carlin-q-scott Fixed
